---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/clock_in":
    post:
      summary: Clock in (start sleep)
      tags:
      - SleepRecords
      parameters:
      - name: X-User-Id
        in: header
        required: true
        schema:
          type: string
      responses:
        '201':
          description: clocked in
        '409':
          description: already clocked in
  "/api/users/{id}/following_sleep_records":
    get:
      summary: Get following users sleep records (last week, sorted by duration)
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: X-User-Id
        in: header
        required: true
        schema:
          type: string
      - name: page
        in: query
        required: false
        schema:
          type: integer
      - name: items
        in: query
        required: false
        schema:
          type: integer
      responses:
        '200':
          description: success
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
